# Overview of NumPy Categories (Part 2):
This notebook provides an overview of two important categories in NumPy:
1. **Linear Algebra (Category 6)**
2. **Statistics and Aggregation (Category 7)**

We will explore common operations in both categories, with emphasis on the differences between MATLAB and NumPy.

## 6. Linear Algebra
• Matrix operations commonly used in algebra and solving systems of equations.
• Functions include `np.linalg.inv()` (matrix inverse), `np.linalg.det()` (matrix determinant), `np.linalg.solve()` (solve a system of linear equations), and `np.linalg.eig()` (eigenvalues and eigenvectors).


<span style="color: red;">In MATLAB, matrix multiplication is done with `*`, and solving Ax = b is done with `A\b`.</span>

<span style="color: green;">In NumPy, matrix multiplication is done with `np.dot()` or `@`, and solving Ax = b is done with `np.linalg.solve(A, b)`.</span>

**MATLAB Example (Solving Ax = b):**
```matlab
A = [3, 1; 1, 2];
b = [9; 8];
x = A\b;  % Solve Ax = b
```

**Python (NumPy) Example (Solving Ax = b):**

In [1]:
import numpy as np
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)  # Solve Ax = b
x

array([2., 3.])

### Determinant and Inverse
• **`np.linalg.inv(A)`** computes the inverse of matrix `A`.
• **`np.linalg.det(A)`** computes the determinant of matrix `A`.

<span style="color: red;">In MATLAB, use `inv(A)` and `det(A)` for matrix inversion and determinant.</span>

<span style="color: green;">In NumPy, use `np.linalg.inv(A)` and `np.linalg.det(A)`.</span>

**MATLAB Example:**
```matlab
A = [3, 1; 1, 2];
invA = inv(A);  % Inverse of A
detA = det(A);  % Determinant of A
```

**Python (NumPy) Example:**

In [3]:
A = np.array([[3, 1], [1, 2]])
invA = np.linalg.inv(A)  # Inverse of A
detA = np.linalg.det(A)  # Determinant of A
invA, detA

(array([[ 0.4, -0.2],
        [-0.2,  0.6]]),
 5.000000000000001)

### Eigenvalues and Eigenvectors
• **`np.linalg.eig(A)`** returns the eigenvalues and eigenvectors of matrix `A`.

<span style="color: red;">In MATLAB, use `eig(A)` to return the eigenvalues and eigenvectors of `A`.</span>

<span style="color: green;">In NumPy, use `np.linalg.eig(A)` to return eigenvalues and eigenvectors.</span>

**MATLAB Example:**
```matlab
A = [1, 2; 2, 3];
[V, D] = eig(A);  % V is the eigenvectors, D is the eigenvalues
```

**Python (NumPy) Example:**

In [4]:
A = np.array([[1, 2], [2, 3]])
eigvals, eigvecs = np.linalg.eig(A)  # Eigenvalues and eigenvectors
eigvals, eigvecs

(array([-0.23606798,  4.23606798]),
 array([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))

## 7. Statistics and Aggregation
• NumPy offers statistical functions such as `np.mean()`, `np.median()`, `np.std()`, `np.sum()`, `np.max()`, and `np.min()`.
• These functions can be applied along a specific axis of an array.


<span style="color: red;">In MATLAB, use `mean(A)`, `std(A)`, `sum(A)` to calculate statistics.</span>

<span style="color: green;">In NumPy, use `np.mean(A)`, `np.std(A)`, `np.sum(A)` to calculate statistics.</span>

**MATLAB Example:**
```matlab
A = [1, 2, 3; 4, 5, 6];
meanA = mean(A);  % Mean of A
sumA = sum(A);    % Sum of A
```

**Python (NumPy) Example:**

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
meanA = np.mean(A)  # Mean of A
sumA = np.sum(A)    # Sum of A
meanA, sumA

(3.5, 21)

### Standard Deviation and Median
• **`np.std(A)`** computes the standard deviation.
• **`np.median(A)`** computes the median.

For computing the standard deviation,

<span style="color: red;">In MATLAB, use `std(A)` to computes the sample standard deviation by default (dividing by  `N-1` ).</span>

<span style="color: green;">In NumPy, use `np.std(A)` computes the population standard deviation by default (dividing by `N` ). To calculate the sample standard deviation, use `np.std(A, ddof=1)`</span>


For computing the mediam,

<span style="color: red;">In MATLAB, use `median(A)`.</span>

<span style="color: green;">In NumPy, use `np.std(A)` and `np.median(A)`.</span>

**MATLAB Example:**
```matlab
A = [1, 2, 3; 4, 5, 6];
stdA = std(A);   % Standard deviation of A
medianA = median(A);  % Median of A
```

**Python (NumPy) Example:**


In [6]:
A = np.array([[1, 2, 3], [4, 5, 6]])
# Population standard deviation (default)
pop_stdA = np.std(A)

# Sample standard deviation (using Bessel's correction with ddof=1)
sample_stdA = np.std(A, ddof=1)
medianA = np.median(A)  # Median of A
pop_stdA, sample_stdA, medianA

(1.707825127659933, 1.8708286933869707, 3.5)